# Site Info
title:              "거창대성고등학교 청원 게시판"
description:        "Designed by Semicolon 2020"
author_name:        "Semicolon"
logo_url:           http://gcdaeseong-h.gne.go.kr/upload/gcdaeseong-h/clubhmpg_10002693/img_3211ba66-deda-4b2c-a7bc-4a91436f27381592636464256.png

# Site Settings
url:                https://gcdstoday.github.io # main url
baseurl:            /the-plain
permalink:          /:title # Post permalink
timezone:           Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
